import 'package:get/get.dart';

///[AppTranslations] creates a class which map keys to values which can be translated depending on locale
class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_UK': {
      'email': 'Email',
      'password': 'Password',
      'login': 'Login',
      'register': 'Register',
      'forgot_password': 'Forgot password?',
      'name': 'Name',
      'no_student':'Not yet a Student？',
      'already_s' : 'Already a Student?',
      'search': 'Search for courses',

      'hello,': 'Hello,',
      'Search': 'Search',
      'all_courses': 'All courses',
      'beginner':'Beginner',
      'intermediate': 'Intermediate',
      'advanced': 'Advanced',
      'currently_active': 'Currently Active',
      'top_picks': 'Top Picks',
      'view_all': 'View all',
      'courses': 'Courses',
      'enrolled': 'Enrolled',
      'ongoing': 'Ongoing',
      'completed': 'Completed',
      'create_shortlist': 'create a shortlist',
      'add_courses': 'Add Courses',
      'timetable': 'Timetable',
      'join_now': 'Join Now',
      'lessons': 'Lessons',
      'for_you': 'For You',
      'oops': 'Oops...something happened',
      'home': 'Home',
      'course': 'Courses',
      'saved': 'Saved',
      'short_list': 'Shortlist',
      'all': 'all',
      'categories': 'Categories',
      'no_result': 'No results found...',
      'start_l': 'Start Learning!',
      'personal': 'Personalise your experience',
      'interest': 'Select Interests',
      'interest_hint': 'You will be offered appropriate courses and groups of '
                       'interrelated courses for a full immersion in the noted area of interest',
      'time_allow': 'Allowable time limit for full time students is',
      'time_limit': '10 hours per week',
      'subject_areas': 'Subject Areas',
      'Skill_level': 'Skill Level',
      'Schedule': 'Schedule',
      'Lessons': 'Lessons',
      'lesson_today': '3 lessons today',
      'join': 'Join Now',
      'Profile': 'Profile',
      'take_photo': 'Take Photo',
      'choose_image': 'Choose Image',
      'Cancel': 'Cancel',
      'User_email': 'User email',
      'Enrolled': 'Enrolled',
      'Active': 'Active',
      'Completed': 'Completed',
      'Common':'Common',
      'Language': 'Language',
      'English':'English',
      'Student_preferences': 'Student Preferences',
      'Security':'Security & Account Settings',
      'Delete_account':'Delete Account',
      'Confirm':'Confirm',
      'delete_sure':'Are you sure you would like to delete your account?',
      'irreversible':'This action is irreversible. Are you sure?',
      'allow_share':'Allow activity sharing',
      'Log_out':'Log out',
      'level_s':'Student\'s Level',
      'Course_Info': 'Course Info',
      'Yayy!':'Yayy! Course Completed!',
      'Complete_Course':'Complete Course',
      'Enroll':'Enroll',
      'Classmates': 'Classmates',
      'no_one_enroll': 'No one has enrolled on this course yet',
      'Recommended':'Recommended',
      'Edit_account': 'Edit Account',
      'Confirm_Changes':'Confirm Changes',
      'change_sure': 'Are you sure you would like to make these changes?',
      'Added_to_saved_courses': 'Added to saved courses',
      'remove_save_courses':'Removed from saved courses',
      'you_not_enroll':'You are not enrolled on any courses...',
      'no_ongoing':'No ongoing courses found...',
      'no_complete':'No completed courses found...',
      'eg_introduction':'eg. Introduction to HTML',
      'No_data':'No data',
      'Search_for':'Search for ',
      'eg. Data Science':'eg. Data Science',
      'easier_to_choose':'Make it easier with less options to choose from',
      'Enrolment_successful':'Enrolment successful',
      'Email':'Email'

    },
    'zh_CN': {
      'email': '邮箱',
      'password': '密码',
      'login': '登陆',
      'register': '注册',
      'forgot_password': '忘记密码?',
      'name': '姓名',
      'no_student':'还不是学生？',
      'already_s':'已有账户？',

      'hello,': '您好',
      'Search': '搜索',
      'all_courses': '所有课程',
      'beginner':'初级学者',
      'intermediate': '进阶学者',
      'advanced': '巅峰学者',
      'currently_active': '正在参与的课程',
      'top_picks': '首选',
      'view_all': '查看全部',
      'courses': '课程',
      'enrolled': '登记',
      'ongoing': '进行中',
      'completed': '已完成',
      'create_shortlist': '创建心愿清单',
      'add_courses': '添加课程',
      'timetable': '时间表',
      'join_now': '现在加入',
      'lessons': '课堂',
      'for_you': '为您推荐',
      'oops': '哦豁，什么地方出错啦？',
      'home': '主页',
      'course': '课程',
      'saved': '清单',
      'short_list': '课程列表',
      'all': '全部',
      'categories': '目录',
      'no_result': '找不到结果...',
      'start_l': '开始学习!',
      'personal': '个性化您的课程',
      'interest': '选择感兴趣的主题',
      'interest_hint': '将为您提供合适且与您兴趣相关的课程，让您完全沉浸在感兴趣的领域中',
      'time_allow': '全日制学生的时间限制为',
      'time_limit': '每周 10 小时',
      'subject_areas': '学科领域',
      'Skill_level': '学力等级',
      'Schedule': '时间表',
      'Lessons': '课堂',
      'lesson_today': '今天有 3 节课',
      'join': '加入',
      'Profile': '简介',
      'take_photo': '拍摄照片',
      'choose_image': '选择照片',
      'Cancel': '取消',
      'User_email': '用户邮箱',
      'Enrolled': '总课程',
      'Active': '进行中',
      'Completed': '已完成',
      'Common':'通用',
      'Language': '语言',
      'English':'中文',
      'Student_preferences':'个人喜好',
      'Security':'安全性与账户设置',
      'Delete_account':'删除账户',
      'Confirm':'确认',
      'delete_sure': '您确认删除账户吗？',
      'irreversible': '这种行为是不可逆转的，您确认吗？',
      'allow_share': '允许共享活动',
      'Log_out': '登出',
      'level_s': '学力等级',
      'Course_Info':'课程信息',
      'Yayy!':'耶！课程已完成！',
      'Complete_Course':'完成课程',
      'Enroll':'登记',
      'Classmates':'同学',
      'no_one_enroll':'还没有学生注册这节课',
      'Recommended':'推荐',
      'Edit_account':'编辑',
      'Confirm_Changes':'确认更改',
      'change_sure': '您确认更改这些吗？',
      'Added_to_saved_courses':'添加到已保存课程',
      'remove_save_courses':'从已保存中删除',
      'you_not_enroll':'您还没有注册任何课程',
      'no_ongoing':'找不到正在进行的课程',
      'no_complete':'找不到已完成的课程',
      'eg_introduction':'例：Introduction to HTML ',
      'No_data':'无结果',
      'Search_for':'搜索',
      'eg. Data Science':'例： Data Science',
      'easier_to_choose':'精简的课程方便更好的选择',
      'Enrolment_successful':'成功注册',
      'Email':'邮箱'
    }
  };
}